STM32_PROJECT_ROOT_DIR = ..

STM32_SRC_DIR = $(STM32_PROJECT_ROOT_DIR)/Core/Src
STM32_INCLUDE_DIR = $(STM32_PROJECT_ROOT_DIR)/Core/Inc

# STM32 Drivers Compilation
STM32_DRIVERS_DIR = $(STM32_PROJECT_ROOT_DIR)/Drivers

STM32_HAL_DRIVERS_DIR = $(STM32_DRIVERS_DIR)/STM32F0xx_HAL_Driver
STM32_HAL_DRIVERS_INC_DIR = $(STM32_HAL_DRIVERS_DIR)/Inc
STM32_HAL_DRIVERS_INC_LEG_DIR = $(STM32_HAL_DRIVERS_DIR)/Legacy

STM32_CMSIS_DRIVERS_DIR = $(STM32_DRIVERS_DIR)/CMSIS
STM32_CMSIS_DRIVERS_INC_DIR = $(STM32_CMSIS_DRIVERS_DIR)/Include
STM32_CMSIS_DRIVERS_ST_INC_DIR = $(STM32_CMSIS_DRIVERS_DIR)/Device/ST/STM32F0xx/Include

STM32_HAL_DRIVERS_SRC_DIR = $(STM32_HAL_DRIVERS_DIR)/Src
STM32_HAL_DRIVERS_OBJ_DIR = Drivers/STM32F0xx_HAL_Driver/Src
STM32_HAL_DRIVERS_SRC = $(wildcard $(STM32_HAL_DRIVERS_SRC_DIR)/*.c)
STM32_HAL_DRIVERS_OBJ = $(patsubst $(STM32_HAL_DRIVERS_SRC_DIR)/%.c, $(STM32_HAL_DRIVERS_OBJ_DIR)/%.o, $(STM32_HAL_DRIVERS_SRC))
$(info $(STM32_HAL_DRIVERS_INC_DIR))

# Driver Flags
STM32_DRIVER_FLAGS = -mcpu=cortex-m0 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER \
										-DSTM32F030x8 \
										-I$(STM32_INCLUDE_DIR) \
										-I$(STM32_HAL_DRIVERS_INC_DIR) \
										-I$(STM32_HAL_DRIVERS_INC_LEG_DIR) \
										-I$(STM32_CMSIS_DRIVERS_INC_DIR) \
										-I$(STM32_CMSIS_DRIVERS_ST_INC_DIR) \
										-O0 -ffunction-sections -fdata-sections -Wall -fstack-usage \
										--specs=nano.specs \
										-mfloat-abi=soft -mthumb 

# Toolchain
CC = arm-none-eabi-gcc

all: $(STM32_HAL_DRIVERS_OBJ)

$(STM32_HAL_DRIVERS_OBJ_DIR)/%.o: $(STM32_HAL_DRIVERS_SRC_DIR)/%.c | $(STM32_HAL_DRIVERS_OBJ_DIR)
	$(CC) $(STM32_DRIVER_FLAGS) -c $< -o $@

$(STM32_HAL_DRIVERS_OBJ_DIR):
	mkdir -p $(STM32_HAL_DRIVERS_OBJ_DIR)
